import Foundation
import CryptoKit
import ConnorGraphCore

public struct ENEXNoteImportAdapter: NoteImportSourceAdapter {
    public let sourceKind: NoteImportSourceKind = .evernoteENEX
    public init() {}
    public func scan(_ request: NoteImportScanRequest) -> AsyncThrowingStream<ImportedNote, Error> { AsyncThrowingStream { continuation in Task.detached(priority: .utility) { let delegate = ENEXStreamDelegate(sourceURL: request.sourceURL, continuation: continuation); guard let parser = XMLParser(contentsOf: request.sourceURL) else { continuation.finish(throwing: NoteImportErrorCode.parseFailed); return }; parser.delegate = delegate; parser.shouldResolveExternalEntities = false; if !parser.parse() { continuation.finish(throwing: parser.parserError ?? NoteImportErrorCode.parseFailed) } else { continuation.finish() } } } }
}

private final class ENEXStreamDelegate: NSObject, XMLParserDelegate, @unchecked Sendable {
    let sourceURL: URL; let continuation: AsyncThrowingStream<ImportedNote, Error>.Continuation; var note: ENEXNoteBuilder?; var element = ""; var buffer = ""; var resource: ENEXResourceBuilder?
    init(sourceURL: URL, continuation: AsyncThrowingStream<ImportedNote, Error>.Continuation) { self.sourceURL = sourceURL; self.continuation = continuation }
    func parser(_ parser: XMLParser, didStartElement elementName: String, namespaceURI: String?, qualifiedName qName: String?, attributes attributeDict: [String : String] = [:]) { element = elementName; buffer = ""; if elementName == "note" { note = ENEXNoteBuilder() }; if elementName == "resource" { resource = ENEXResourceBuilder() } }
    func parser(_ parser: XMLParser, foundCharacters string: String) { buffer += string }
    func parser(_ parser: XMLParser, didEndElement elementName: String, namespaceURI: String?, qualifiedName qName: String?) { let value = buffer.trimmingCharacters(in: .whitespacesAndNewlines); if var resource { switch elementName { case "data": resource.base64 = value; case "mime": resource.mime = value; case "file-name": resource.filename = value; case "resource": if let built = try? resource.build() { note?.resources[built.hash] = built }; self.resource = nil; default: break }; if self.resource != nil { self.resource = resource } } else if var note { switch elementName { case "title": note.title = value; case "content": note.content = buffer; case "created": note.created = value; case "updated": note.updated = value; case "tag": if !value.isEmpty { note.tags.append(value) }; case "guid": note.guid = value; case "note": if let built = try? note.build(sourceURL: sourceURL) { continuation.yield(built) }; self.note = nil; default: break }; if self.note != nil { self.note = note } }; buffer = "" }
}

private struct ENEXResourceBuilder { var base64 = ""; var mime = "application/octet-stream"; var filename = "resource"; func build() throws -> ENEXResource { guard let data = Data(base64Encoded: base64, options: [.ignoreUnknownCharacters]) else { throw NoteImportErrorCode.parseFailed }; let hash = Insecure.MD5.hash(data: data).map { String(format: "%02x", $0) }.joined(); let dir = FileManager.default.temporaryDirectory.appendingPathComponent("connor-enex-resources", isDirectory: true); try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true); let url = dir.appendingPathComponent(hash + "-" + AppSessionAttachmentStore.sanitizedFilename(filename)); try data.write(to: url, options: .atomic); return ENEXResource(hash: hash, mime: mime, filename: filename, url: url, bytes: Int64(data.count)) } }
private struct ENEXResource { var hash: String; var mime: String; var filename: String; var url: URL; var bytes: Int64 }
private struct ENEXNoteBuilder { var title = "Untitled"; var content = ""; var created = ""; var updated = ""; var guid = ""; var tags: [String] = []; var resources: [String: ENEXResource] = [:]
    func build(sourceURL: URL) throws -> ImportedNote { var markdown = content.replacingOccurrences(of: "(?is)<script.*?</script>", with: "", options: .regularExpression).replacingOccurrences(of: "(?i)<en-todo[^>]*checked=\"true\"[^>]*/?>", with: "- [x] ", options: .regularExpression).replacingOccurrences(of: "(?i)<en-todo[^>]*/?>", with: "- [ ] ", options: .regularExpression).replacingOccurrences(of: "(?i)<br\\s*/?>", with: "\n", options: .regularExpression).replacingOccurrences(of: "(?i)</(div|p|li|h[1-6])>", with: "\n", options: .regularExpression); let mediaRegex = try NSRegularExpression(pattern: "(?i)<en-media[^>]*hash=\"([0-9a-f]+)\"[^>]*/?>"); let ns = markdown as NSString; var attachments: [ImportedNoteAttachment] = []; for match in mediaRegex.matches(in: markdown, range: NSRange(location: 0, length: ns.length)).reversed() { let hash = ns.substring(with: match.range(at: 1)).lowercased(); if let resource = resources[hash] { attachments.append(.init(sourcePath: resource.url.path, displayName: resource.filename, mimeType: resource.mime, byteCount: resource.bytes, metadata: ["enex_md5": hash])); let replacement = "![\(resource.filename)](attachment:\(hash))"; markdown = (markdown as NSString).replacingCharacters(in: match.range, with: replacement) } }; markdown = markdown.replacingOccurrences(of: "<[^>]+>", with: "", options: .regularExpression).replacingOccurrences(of: "&amp;", with: "&").replacingOccurrences(of: "&lt;", with: "<").replacingOccurrences(of: "&gt;", with: ">"); let data = Data(markdown.utf8); return ImportedNote(sourceKind: .evernoteENEX, sourceIdentity: guid.isEmpty ? title + created : guid, externalID: guid.isEmpty ? nil : guid, sourcePath: sourceURL.path, title: title, markdownContent: markdown, createdAt: Self.date(created), updatedAt: Self.date(updated), tags: tags, attachments: attachments, sourceMetadata: ["enex_notebook": sourceURL.deletingPathExtension().lastPathComponent], rawByteHash: SHA256.hash(data: data).hexString, normalizedTextHash: SHA256.hash(data: data).hexString) }
    static func date(_ value: String) -> Date? { let f = DateFormatter(); f.locale = Locale(identifier: "en_US_POSIX"); f.timeZone = TimeZone(secondsFromGMT: 0); f.dateFormat = "yyyyMMdd'T'HHmmss'Z'"; return f.date(from: value) }
}
private extension Digest { var hexString: String { map { String(format: "%02x", $0) }.joined() } }
