import Foundation
import CryptoKit
import ConnorGraphCore

public enum NotionDatabaseImportStrategy: String, Sendable, Codable { case childPagesOnly = "child_pages_only"; case databaseSummary = "database_summary"; case rowAsNote = "row_as_note" }

public struct NotionExportNoteImportAdapter: NoteImportSourceAdapter {
    public let sourceKind: NoteImportSourceKind = .notionExport
    public var databaseStrategy: NotionDatabaseImportStrategy
    public init(databaseStrategy: NotionDatabaseImportStrategy = .childPagesOnly) { self.databaseStrategy = databaseStrategy }
    public func scan(_ request: NoteImportScanRequest) -> AsyncThrowingStream<ImportedNote, Error> { AsyncThrowingStream { continuation in Task.detached(priority: .utility) { do { for note in try Self.notes(root: request.sourceURL, strategy: databaseStrategy) { continuation.yield(note) }; continuation.finish() } catch { continuation.finish(throwing: error) } } } }

    private static func notes(root: URL, strategy: NotionDatabaseImportStrategy) throws -> [ImportedNote] {
        guard let enumerator = FileManager.default.enumerator(at: root, includingPropertiesForKeys: [.isRegularFileKey], options: [.skipsHiddenFiles]) else { return [] }
        var result: [ImportedNote] = []
        for case let url as URL in enumerator { let ext = url.pathExtension.lowercased(); guard ["md", "markdown", "html", "htm", "csv"].contains(ext) else { continue }; if ext == "csv" && strategy == .childPagesOnly { continue }
            let data = try Data(contentsOf: url); let text = String(decoding: data, as: UTF8.self); let relative = url.path.replacingOccurrences(of: root.path + "/", with: ""); let parsed = parseName(url.deletingPathExtension().lastPathComponent); let hierarchy = relative.split(separator: "/").dropLast().map(String.init)
            if ext == "csv" && strategy == .rowAsNote { let rows = parseCSV(text); guard let headers = rows.first else { continue }; for (index, row) in rows.dropFirst().enumerated() { let pairs = zip(headers, row).map { "- **\($0.0):** \($0.1)" }.joined(separator: "\n"); result.append(make(kind: ext, title: row.first?.nilIfEmpty ?? "\(parsed.title) \(index + 1)", content: pairs, relative: relative + "#row-\(index + 1)", externalID: nil, hierarchy: hierarchy, data: Data(pairs.utf8), root: root, sourceURL: url)) }; continue }
            let content = ext.hasPrefix("htm") ? sanitizeHTML(text) : (ext == "csv" ? csvSummary(text, title: parsed.title) : text)
            result.append(make(kind: ext, title: parsed.title, content: content, relative: relative, externalID: parsed.id, hierarchy: hierarchy, data: data, root: root, sourceURL: url))
        }
        return result
    }
    private static func make(kind: String, title: String, content: String, relative: String, externalID: String?, hierarchy: [String], data: Data, root: URL, sourceURL: URL) -> ImportedNote { let assets = assetLinks(content).compactMap { raw -> ImportedNoteAttachment? in let decoded = raw.removingPercentEncoding ?? raw; let url = sourceURL.deletingLastPathComponent().appendingPathComponent(decoded); guard FileManager.default.fileExists(atPath: url.path), !["md", "html", "htm", "csv"].contains(url.pathExtension.lowercased()) else { return nil }; return .init(sourcePath: url.path, displayName: url.lastPathComponent, byteCount: try? AppSessionAttachmentStore.byteCount(forItemAt: url), contentHash: try? AppSessionAttachmentStore.sha256Hex(forItemAt: url)) }; return ImportedNote(sourceKind: .notionExport, sourceIdentity: externalID ?? relative.lowercased(), externalID: externalID, sourcePath: sourceURL.path, relativePath: relative, title: title, markdownContent: content, hierarchy: hierarchy, attachments: assets, sourceMetadata: ["notion_format": kind], rawByteHash: SHA256.hash(data: data).hex, normalizedTextHash: SHA256.hash(data: Data(content.replacingOccurrences(of: "\r\n", with: "\n").utf8)).hex) }
    private static func parseName(_ value: String) -> (title: String, id: String?) { let regex = try! NSRegularExpression(pattern: "^(.*) ([0-9a-fA-F]{32})$"); let ns = value as NSString; guard let match = regex.firstMatch(in: value, range: NSRange(location: 0, length: ns.length)) else { return (value, nil) }; return (ns.substring(with: match.range(at: 1)), ns.substring(with: match.range(at: 2))) }
    private static func sanitizeHTML(_ html: String) -> String { var value = html.replacingOccurrences(of: "(?is)<script.*?</script>", with: "", options: .regularExpression).replacingOccurrences(of: "(?is)<style.*?</style>", with: "", options: .regularExpression); value = value.replacingOccurrences(of: "(?i)<br\\s*/?>", with: "\n", options: .regularExpression).replacingOccurrences(of: "(?i)</(p|div|li|h[1-6])>", with: "\n", options: .regularExpression).replacingOccurrences(of: "<[^>]+>", with: "", options: .regularExpression); return value.replacingOccurrences(of: "&amp;", with: "&").replacingOccurrences(of: "&lt;", with: "<").replacingOccurrences(of: "&gt;", with: ">") }
    private static func assetLinks(_ text: String) -> [String] { let regex = try! NSRegularExpression(pattern: "!?\\[[^\\]]*\\]\\(([^)]+)\\)"); let ns = text as NSString; return regex.matches(in: text, range: NSRange(location: 0, length: ns.length)).map { ns.substring(with: $0.range(at: 1)).components(separatedBy: "#")[0] } }
    private static func csvSummary(_ csv: String, title: String) -> String { let rows = parseCSV(csv); return "# \(title)\n\n数据库导出，共 \(max(rows.count - 1, 0)) 行。\n\n" + rows.prefix(20).map { "| " + $0.joined(separator: " | ") + " |" }.joined(separator: "\n") }
    private static func parseCSV(_ text: String) -> [[String]] { var rows: [[String]] = [], row: [String] = [], field = ""; var quoted = false; let chars = Array(text); var i = 0; while i < chars.count { let c = chars[i]; if c == "\"" { if quoted && i + 1 < chars.count && chars[i + 1] == "\"" { field.append("\""); i += 1 } else { quoted.toggle() } } else if c == "," && !quoted { row.append(field); field = "" } else if (c == "\n" || c == "\r") && !quoted { if c == "\r" && i + 1 < chars.count && chars[i + 1] == "\n" { i += 1 }; row.append(field); rows.append(row); row = []; field = "" } else { field.append(c) }; i += 1 }; if !field.isEmpty || !row.isEmpty { row.append(field); rows.append(row) }; return rows }
}
private extension Digest { var hex: String { map { String(format: "%02x", $0) }.joined() } }
private extension String { var nilIfEmpty: String? { isEmpty ? nil : self } }
